export const mockProducts = [
  {
    id: "product-1",
    name: "Ergonomic Office Chair",
    slug: "ergonomic-office-chair",
    description: "Comfortable chair with lumbar support",
    price: 299.99,
    category: "Office",
    isActive: true,
    isHighlighted: true,
    imageUrl: "/placeholder.svg?height=200&width=200",
    images: [],
    userId: "user-1",
    catalogs: [],
    createdAt: new Date("2025-01-10T09:00:00Z"),
    updatedAt: new Date("2025-01-10T09:00:00Z"),
  },
  {
    id: "product-2",
    name: "Wireless Bluetooth Headphones",
    slug: "wireless-bluetooth-headphones",
    description: "Noise-cancelling with 30-hour battery life",
    price: 149.99,
    category: "Electronics",
    isActive: true,
    isHighlighted: false,
    imageUrl: "/placeholder.svg?height=200&width=200",
    images: [],
    userId: "user-1",
    catalogs: [],
    createdAt: new Date("2025-01-11T09:00:00Z"),
    updatedAt: new Date("2025-01-11T09:00:00Z"),
  },
  // (adicione os demais produtos com os mesmos campos e formatos)
]

export const mockCatalogs = [
  {
    id: "catalog-1",
    name: "Summer Collection 2025",
    slug: "summer-collection-2025",
    description: "Our latest summer products with special discounts",
    logo: "/placeholder.svg?height=400&width=800",
    isActive: true,
    userId: "user-1",
    products: [],
    createdAt: new Date("2025-01-15T12:00:00Z"),
    updatedAt: new Date("2025-01-15T12:00:00Z"),
  },
  {
    id: "catalog-2",
    name: "Office Essentials",
    slug: "office-essentials",
    description: "Everything you need for your workspace",
    logo: "/placeholder.svg?height=400&width=800",
    isActive: true,
    userId: "user-1",
    products: [],
    createdAt: new Date("2025-01-10T09:30:00Z"),
    updatedAt: new Date("2025-01-10T09:30:00Z"),
  },
  {
    id: "catalog-3",
    name: "Tech Gadgets 2025",
    slug: "tech-gadgets-2025",
    description: "The latest technology for your everyday needs",
    logo: "/placeholder.svg?height=400&width=800",
    isActive: false,
    userId: "user-1",
    products: [],
    createdAt: new Date("2025-01-05T15:45:00Z"),
    updatedAt: new Date("2025-01-05T15:45:00Z"),
  },
  // (adicione os demais catálogos com o mesmo padrão)
]
